### ISSUE TITLE
mailers for newsletters/password resetting should be incorporated

### ISSUE THREAD

**Issue by CRiva** [HParker/horizon#10]

**Comment by HParker** [comment]
@CRiva Can I close this? I recall you saying this works now.

**Comment by CRiva** [comment]
@HParker well, you still can't subscribe to receive new articles via email, but sure, the important thing got done.

**Comment by HParker** [comment]
Feel free to create another issue for that, though I likely won't pick it up since it will require knowing about the mail configuration.
